"""Initial migration

Revision ID: 17862a79a853
Revises: 
Create Date: 2026-01-04 09:19:46.428323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17862a79a853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('shop_slug', sa.String(length=100), nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=True),
    sa.Column('shopify_access_token', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=100), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quick_flip_days', sa.Integer(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('member_number', sa.String(length=20), nullable=False),
    sa.Column('shopify_customer_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('membership_start_date', sa.Date(), nullable=True),
    sa.Column('membership_end_date', sa.Date(), nullable=True),
    sa.Column('total_bonus_earned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_trade_ins', sa.Integer(), nullable=True),
    sa.Column('total_trade_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'member_number', name='uq_tenant_member_number')
    )
    op.create_table('trade_in_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('batch_reference', sa.String(length=50), nullable=False),
    sa.Column('trade_in_date', sa.DateTime(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_trade_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_reference')
    )
    op.create_table('trade_in_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=50), nullable=True),
    sa.Column('product_title', sa.String(length=500), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('trade_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('listing_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('listed_date', sa.DateTime(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shopify_order_id', sa.String(length=50), nullable=True),
    sa.Column('days_to_sell', sa.Integer(), nullable=True),
    sa.Column('eligible_for_bonus', sa.Boolean(), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['trade_in_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('trade_in_item_id', sa.Integer(), nullable=True),
    sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('store_credit_txn_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('days_to_sell', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['trade_in_item_id'], ['trade_in_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bonus_transactions')
    op.drop_table('trade_in_items')
    op.drop_table('trade_in_batches')
    op.drop_table('members')
    op.drop_table('membership_tiers')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    # ### end Alembic commands ###
